services:
  db:
    env_file:
      - .env.dev
    image: mysql:8.0.39-debian
    container_name: db
    volumes:
      - data_prod:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: clave123
      MYSQL_DATABASE: Cervezario
    ports:
      - "3306:3306"
    platform: linux/amd64
    restart: always

  flyway:
    image: flyway/flyway:10.20.1-alpine
    volumes:
      - ../../../grupo-2-backend/db/script-creacion:/flyway/sql
    command: "-url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME} -user=${DB_USER} -password=${DB_PASSWORD} -connectRetries=60 migrate"
    container_name: flyway
    depends_on:
      - db
    restart: always
  backend:
    env_file:
      - .env.dev
    image: kmreyes/cervezarionacional:2.2.3
    ports:
      - "4500:4500"
    command: "npm run start:prod"
    platform: linux/amd64
    container_name: backend
    depends_on:
      - db
    volumes:
      - ./imagenes-cervezas:/home/node/app/imagenes-cervezas
    restart: always

  front:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    depends_on:
      - backend
    restart: always
    container_name: frontend

    ports:
      - "${FRONT_PORT}:80"

volumes:
  data_prod:
