services:
  db:
    image: mysql:8.0.39-debian
    container_name: db
    volumes:
      - data_prod:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: clave123
      MYSQL_DATABASE: Cervezario
    ports:
      - "3306:3306"
    platform: linux/amd64
    restart: always

  flyway:
    image: flyway/flyway:10.20.1-alpine
    volumes:
      - ../grupo-2-backend/db/script-creacion:/flyway/sql
    command: "-url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME} -user=${DB_USER} -password=${DB_PASSWORD} -connectRetries=60 migrate"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    restart: always
  cervezario-app-prod:
    image: kmreyes/cervezarionacional:2.2.3
    environment:
      - APP_NAME=${APP_NAME}
      - APP_VERSION=${APP_VERSION}
      - NESTJS_PORT=${NESTJS_PORT}
      - AMBIENTE=${AMBIENTE}
      - NODE_VERSION=${NODE_VERSION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "4500:4500"
    command: "npm run start:prod"
    platform: linux/amd64
    depends_on:
      - db
    restart: always

  front:
    image: calvegh337/entrega-10:deploy
    depends_on:
      - cervezario-app-prod
    ports:
      - "5174:80"
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - cervezario-app-prod
      - front
    restart: always
volumes:
  data_prod:
