services:
  cervezario-app-prod:
    image: kmreyes/cervezarionacional:2.0.1
    env_file:
      - .env
    ports:
      - "4500:4500"
    command: "npm run start:prod"
    platform: linux/amd64
    depends_on:
      - db
  db:
    image: mysql:8.0.39-debian
    environment:
      MYSQL_ROOT_PASSWORD: clave123
      MYSQL_DATABASE: Cervezario
    volumes:
      - ./db/scripts-creacion/creacion-db.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/scripts-creacion/datos.sql:/docker-entrypoint-initdb.d/2.sql
      - data_prod:/var/lib/mysql
    ports:
      - "3306:3306"
    platform: linux/amd64
  front:
    image: mankekez/cervezario-front-dev
    depends_on:
      - cervezario-app-prod
    ports:
      - "5173:80"
volumes:
  data_prod: