services:
  db:
    env_file:
      - ../../.env.prod
    image: mysql:8.0.39-debian
    container_name: db
    volumes:
      - data_prod:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    platform: linux/amd64
    restart: always

  flyway:
    image: flyway/flyway:10.20.1-alpine
    volumes:
      - ../../../grupo-2-backend/db/script-creacion:/flyway/sql
    command: >
      -url=jdbc:mysql://db:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true
      -user=${DB_USER}
      -password=${DB_PASS_ROOT}
      -connectRetries=60
      migrate
    container_name: flyway
    depends_on:
      db:
        condition: service_started
    restart: always

  backend:
    env_file:
      - ../../.env.prod
    image: kmreyes/cervezarionacional:3.2.0
    ports:
      - "4500:4500"
    platform: linux/amd64
    container_name: backend
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./imagenes-cervezas:/home/node/app/imagenes-cervezas
    restart: always

  front:
    image: calvegh337/cervezario-front
    depends_on:
      - backend
    restart: always
    container_name: frontend
    ports:
      - "${PORT_FRONT}:80"

volumes:
  data_prod:
